config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"
  resources :vehicle_services
  resources :closures, only: [:index,:new,:create] do 
    get 'show_tickets', on: :collection
    get 'modal_send_report', on: :member
    post 'set_was_send', on: :member
  end
  resources :ticket_books do 
    get 'get_tickets', on: :member
    get 'modal_closed', on: :member
    put 'set_closed', on: :member
    post "disable", on: :collection
  end
  resources :tickets, except: [:destroy] do
    get "modal_change_status", on: :member
    post "change_status", on: :member
    get "modal_detail_disable", on: :member
  end
  resources :fuel_suppliers
  resources :fuel_to_vehicles do
    get 'import_excel', on: :collection
  end
  resources :fuel_loads
  root 'main#welcome'
  get 'main/welcome'

  resources :people_clothes, only: [:index, :show,:new, :create, :edit, :update] do 
    post "disable", on: :collection
  end
  post 'disable_people_clothe', to: 'people_clothes#disable', as: 'disable_people_clothe'
  resources :clothes, only: [:index, :new, :create, :edit, :update]
  post 'disable_clothe', to: 'clothes#disable', as: 'disable_clothe'
  resources :clothing_packages
  post 'disable_clothing_package', to: 'clothing_packages#disable', as: 'disable_clothing_package'
  post 'disable_clothes_pack', to: "clothes_packs#disable", as: "disable_clothes_pack" # elimino una prenda de ropa de un package
  resources :insurances
  resources :vehicle_insurances do 
    get 'show_files', on: :collection
  end
  post 'disable_insurance', to: 'insurances#disable', as: 'disable_insurance'

  resources :vehicles, except: [:destroy] do 
    get 'show_images', on: :member
    get 'get_images', on: :member
    get 'show_vehicle_history', on: :member
    get 'modal_enable_vehicle', on: :member
    post :delete_image_attachment, on: :collection
    get 'status_mileage_for_service', on: :member
    get 'admin_units_load', on: :collection
  end
  post 'disable_vehicle', to: 'vehicles#disable', as: 'disable_vehicle'
  get 'inactives_vehicles', to: 'vehicles#inactives', as: 'inactives_vehicles'

  get 'vehicles/:id/show_vehicle_history', to: 'vehicles#show_vehicle_history', as: 'show_vehicle_history'
  get 'vehicles/:id/modal_enable_vehicle', to: 'vehicles#modal_enable_vehicle', as: 'modal_enable_vehicle'
  post 'vehicles/enable_vehicle', to: 'vehicles#enable_vehicle', as: 'enable_vehicle'
  resources :vehicle_locations
  
  resources :vehicle_models
  post 'disable_vehicle_model', to: 'vehicle_models#disable', as: 'disable_vehicle_model'
  
  resources :vehicle_brands, except: [:destroy]
  post 'disable_vehicle_brand', to: 'vehicle_brands#disable', as: 'disable_vehicle_brand'
  
  resources :vehicle_types, except: [:destroy]
  post 'disable_vehicle_type', to: 'vehicle_types#disable', as: 'disable_vehicle_type'
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create, :edit, :update]
      post 'disable_user', to: 'users#disable', as: 'disable_user'
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
  
  get 'person_dato_disponible', to: 'people#dato_disponible', as: 'person_dato_disponible'
  get '/people/:id/upload_person_file/:file', to: 'people#upload_person_file', as: 'upload_person_file'
  resources :people, except: [:destroy] do 
    get "permission_fuel_load", on: :collection
    post 'set_permission', on: :member
  end
  post 'disable_person', to: 'people#disable', as: 'disable_person'
  get 'inactive_people', to: 'people#inactives', as: 'inactive_people'
  get 'people/:id/show_person_history', to: 'people#show_person_history', as: 'show_person_history'
  get 'people/:id/modal_enable_person', to: 'people#modal_enable_person', as: 'modal_enable_person'
  post 'people/enable_person', to: 'people#enable_person', as: 'enable_person'
  resources :companies, except: [:destroy, :show]
  post 'disable_company', to: 'companies#disable', as: 'disable_company'
  resources :profiles, except: [:destroy, :show]
  post 'disable_profile', to: 'profiles#disable', as: 'disable_profile'
  resources :documents
  post 'disable_document', to: 'documents#disable', as: 'disable_document'
  resources :document_categories
  resources :expiration_types
  
  get 'documents_profiles/:id/modal_disable', to: 'documents_profiles#modal_disable', as: 'modal_disable_document_profile'
  resources :documents_profiles, except: [:destroy, :show]
  post 'disable_document_profile', to: 'documents_profiles#disable', as: 'disable_document_profile'
  
  resources :people_profiles, except: [:destroy, :show]
  resources :vehicles_profiles, except: [:destroy, :show] 

  resources :assignments_profiles, except: [:index, :destroy]
  post 'disable_assignment_profile', to: 'assignments_profiles#disable', as: 'disable_assignment_profile'
  post 'reactive_profile_assignment_profile', to: 'assignments_profiles#reactive_profile', as: 'reactive_profile_assignment_profile'

  resources :assignments_documents, except: [:index, :destroy]
  get 'assignments_documents/:id/modal_disable', to: 'assignments_documents#modal_disable', as: 'modal_disable_assignments_documents'
  post 'disable_assignments_documents', to: 'assignments_documents#disable', as: 'disable_assignments_documents'

  get 'status_documentation/people'
  get 'status_documentation/vehicles'

  resources :document_renovations do 
    get 'show_files'
  end
  post 'disable_document_renovation', to: 'document_renovations#disable', as: 'disable_document_renovation'

  resources :reasons_to_disables, except: [:destroy, :show]
  post 'disable_reason', to: 'reasons_to_disables#disable', as: 'disable_reason'

  resources :reports, only: [:index] do
    get 'modal_fuel_report', on: :collection
    get 'people', on: :collection
    get 'people_documents', on: :collection
    post 'people_documents', on: :collection
    get 'matriz_vehicles', on: :collection
    get 'fuel', on: :collection
    get 'by_closure', on: :collection
  end

  namespace :reports do
    get 'document_expirations', to: 'vehicles#document_expirations'
    post 'document_expirations', to: 'vehicles#document_expirations'
    resources :vehicles, only: [:index]
    #   post 'disable_user', to: 'users#disable', as: 'disable_user'
    # resources :sessions, only: [:create]
    # get 'login', to: 'sessions#new', as: 'login'
    # get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/vehicle_brand.rb
# == Schema Information
#
# Table name: vehicle_brands
#
#  id          :bigint           not null, primary key
#  name        :string(255)      not null
#  description :string(255)
#  active      :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class VehicleBrand < ApplicationRecord
	validates :name, presence: true, 
		uniqueness: { case_sensitive: false, message: "La marca ya se encuentra registrada" }

	scope :actives, -> { where(active: true) }
	
end

app/controllers/vehicle_brands_controller.rb
class VehicleBrandsController < ApplicationController
  before_action :set_vehicle_brand, only: %i[ show edit update destroy ]

  # GET /vehicle_brands or /vehicle_brands.json
  def index
    @vehicle_brands = VehicleBrand.actives
    @vehicle_brand = VehicleBrand.new
  end

  # GET /vehicle_brands/1 or /vehicle_brands/1.json
  def show
  end

  # GET /vehicle_brands/new
  def new
    @vehicle_brand = VehicleBrand.new
  end

  # GET /vehicle_brands/1/edit
  def edit
  end

  # POST /vehicle_brands or /vehicle_brands.json
  def create
    @vehicle_brand = VehicleBrand.new(vehicle_brand_params)
    activity_history = ActivityHistory.new( action: :create_record, description: "Se registro la marca de vehículo #{@vehicle_brand.name}", 
      record: @vehicle_brand, date: Time.now, user: current_user )
    respond_to do |format|
      if @vehicle_brand.save && activity_history.save
        format.json { render json: { status: 'success', msg: 'Marca registrada' }, status: :created}
        format.html { redirect_to vehicle_brand_url(@vehicle_brand), notice: "Vehicle brand was successfully created." }
      else
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_brands/1 or /vehicle_brands/1.json
  def update
    respond_to do |format|
      if @vehicle_brand.update(vehicle_brand_params)
        format.json { render json: { status: 'success', msg: 'Marca actualizada' }, status: :ok}
        format.html { redirect_to vehicle_brand_url(@vehicle_brand), notice: "Vehicle brand was successfully updated." }
      else
        format.json { render json: @vehicle_brand.errors, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def disable
    vehicle_brand = VehicleBrand.find(params[:vehicle_brand_id])
    activity_history = ActivityHistory.new( action: :disable, description: "Se dio de baja la marca de vehículo #{vehicle_brand.name}", 
      record: vehicle_brand, date: Time.now, user: current_user )
    
    respond_to do |format|
      if vehicle_brand.update(active: false) && activity_history.save
        format.json { render json: { status: 'success', msg: 'Marca dada de baja' }, status: :ok }
      else
        format.json { render json: { status: 'error', msg: 'No se pudo dar de baja la marca', errors: vehicle_brand.errors }, status: :unprocessable_entity }
      end # commit
    end # respond_to
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_brand
      @vehicle_brand = VehicleBrand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_brand_params
      params.require(:vehicle_brand).permit(:name, :active, :description)
    end
end

app/views/vehicle_brands/_form.html.erb
<%= form_with(model: vehicle_brand, local: true) do |form| %>
  <% if vehicle_brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_brand.errors.count, "error") %> prohibited this vehicle_brand from being saved:</h2>

      <ul>
      <% vehicle_brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_brands/_index.html.erb
<small>Registrar marca:</small>
<%= form_with(model: @vehicle_brand, class: "form-inline mb-2", id: "form-vehicle-brand") do |form| %>
  <div class="form-group mr-2">
    <%= form.label :name, 'Nombre: ',class:"col-form-label mr-1" %>
    <%= form.text_field :name, class: "form-control form-control-sm", placeholder: 'Ingrese nombre de marca', required: true %>
    <small class="form-control-feedback text-danger vehicle_brand_name"></small>
  </div>
  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-primary' %>
  </div>
<% end %>

<div class="card g-brd-purple %> rounded g-mb-30">
  <h3 class="card-header g-bg-purple g-brd-transparent g-color-white g-font-size-16 mb-2 rounded-0">
    <i class="fa fa-car"></i>
    Marcas de vehículos
  </h3>
   <div class="px-2  pb-2">
    <table id="vehicle_brands_table" class="table table-sm table-hover dt-responsive w-100 u-table--v1" data-show='show'>
      <thead>
        <tr>
          <th>Marca</th>
          <th>Acciones</th>
        </tr>
      </thead>

      <tbody>
        <!-- Completo con ajax -->
      </tbody>
    </table>
  </div>
</div>

<!-- Modal para eliminar marca de vehiculo -->
<div class="modal fade" id="modal-disable-vehicle-brand" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de dar de baja esta marca ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: disable_vehicle_brand_path, id: 'form-disable-vehicle-brand') do |form| %>
          <%= form.hidden_field :vehicle_brand_id %>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" class="btn u-btn-teal g-mr-10" onclick="close_modal('modal-disable-vehicle-brand')"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar marca de vehiculo -->

app/views/vehicle_brands/edit.html.erb
<h1>Editing Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Show', @vehicle_brand %> |
<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/index.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'index' } ) %>")

$(document).ready(function(){
  vehicles_brands_table = $("#vehicle_brands_table").DataTable({
    'ajax': `vehicle_brands`,
    'columns': [
    {'data': 'name'},
    {'data': 'actions'}
    ],
    'language': {'url': datatables_lang}
  })

	$("#form-vehicle-brand").on("ajax:success", function(event) {
	    vehicles_brands_table.ajax.reload(null,false)
	    clean_form('form-vehicle-brand')
      let msg = JSON.parse(event.detail[2].response)
      noty_alert(msg.status, msg.msg)
	  }).on("ajax:error", function(event) {
		let msg = JSON.parse( event.detail[2].response )
		set_input_status_form('form-vehicle-brand', 'vehicle_brand', msg)
	})

  $("#form-disable-vehicle-brand").on("ajax:success", function(event) {
    vehicles_brands_table.ajax.reload(null,false)
    let msj = JSON.parse(event.detail[2].response)
    noty_alert(msj.status, msj.msg)
    $("#modal-disable-vehicle-brand").modal('hide')
  }).on("ajax:error", function(event) {
    noty_alert('error', 'No se pudo eliminar esta marca')
  })

})

$("#modal").modal('show')

app/views/vehicle_brands/new.html.erb
<h1>New Vehicle Brand</h1>

<%= render 'form', vehicle_brand: @vehicle_brand %>

<%= link_to 'Back', vehicle_brands_path %>

app/views/vehicle_brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vehicle_brand.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @vehicle_brand.active %>
</p>

<p>
  <strong>Description:</strong>
  <%= @vehicle_brand.description %>
</p>

<%= link_to 'Edit', edit_vehicle_brand_path(@vehicle_brand) %> |
<%= link_to 'Back', vehicle_brands_path %>