config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"
  resources :vehicle_services
  resources :closures, only: [:index,:new,:create] do 
    get 'show_tickets', on: :collection
    get 'modal_send_report', on: :member
    post 'set_was_send', on: :member
  end
  resources :ticket_books do 
    get 'get_tickets', on: :member
    get 'modal_closed', on: :member
    put 'set_closed', on: :member
    post "disable", on: :collection
  end
  resources :tickets, except: [:destroy] do
    get "modal_change_status", on: :member
    post "change_status", on: :member
    get "modal_detail_disable", on: :member
  end
  resources :fuel_suppliers
  resources :fuel_to_vehicles do
    get 'import_excel', on: :collection
  end
  resources :fuel_loads
  root 'main#welcome'
  get 'main/welcome'

  resources :people_clothes, only: [:index, :show,:new, :create, :edit, :update] do 
    post "disable", on: :collection
  end
  post 'disable_people_clothe', to: 'people_clothes#disable', as: 'disable_people_clothe'
  resources :clothes, only: [:index, :new, :create, :edit, :update]
  post 'disable_clothe', to: 'clothes#disable', as: 'disable_clothe'
  resources :clothing_packages
  post 'disable_clothing_package', to: 'clothing_packages#disable', as: 'disable_clothing_package'
  post 'disable_clothes_pack', to: "clothes_packs#disable", as: "disable_clothes_pack" # elimino una prenda de ropa de un package
  resources :insurances
  resources :vehicle_insurances do 
    get 'show_files', on: :collection
  end
  post 'disable_insurance', to: 'insurances#disable', as: 'disable_insurance'

  resources :vehicles, except: [:destroy] do 
    get 'show_images', on: :member
    get 'get_images', on: :member
    get 'show_vehicle_history', on: :member
    get 'modal_enable_vehicle', on: :member
    post :delete_image_attachment, on: :collection
    get 'status_mileage_for_service', on: :member
    get 'admin_units_load', on: :collection
  end
  post 'disable_vehicle', to: 'vehicles#disable', as: 'disable_vehicle'
  get 'inactives_vehicles', to: 'vehicles#inactives', as: 'inactives_vehicles'

  get 'vehicles/:id/show_vehicle_history', to: 'vehicles#show_vehicle_history', as: 'show_vehicle_history'
  get 'vehicles/:id/modal_enable_vehicle', to: 'vehicles#modal_enable_vehicle', as: 'modal_enable_vehicle'
  post 'vehicles/enable_vehicle', to: 'vehicles#enable_vehicle', as: 'enable_vehicle'
  resources :vehicle_locations
  
  resources :vehicle_models
  post 'disable_vehicle_model', to: 'vehicle_models#disable', as: 'disable_vehicle_model'
  
  resources :vehicle_brands, except: [:destroy]
  post 'disable_vehicle_brand', to: 'vehicle_brands#disable', as: 'disable_vehicle_brand'
  
  resources :vehicle_types, except: [:destroy]
  post 'disable_vehicle_type', to: 'vehicle_types#disable', as: 'disable_vehicle_type'
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create, :edit, :update]
      post 'disable_user', to: 'users#disable', as: 'disable_user'
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
  
  get 'person_dato_disponible', to: 'people#dato_disponible', as: 'person_dato_disponible'
  get '/people/:id/upload_person_file/:file', to: 'people#upload_person_file', as: 'upload_person_file'
  resources :people, except: [:destroy] do 
    get "permission_fuel_load", on: :collection
    post 'set_permission', on: :member
  end
  post 'disable_person', to: 'people#disable', as: 'disable_person'
  get 'inactive_people', to: 'people#inactives', as: 'inactive_people'
  get 'people/:id/show_person_history', to: 'people#show_person_history', as: 'show_person_history'
  get 'people/:id/modal_enable_person', to: 'people#modal_enable_person', as: 'modal_enable_person'
  post 'people/enable_person', to: 'people#enable_person', as: 'enable_person'
  resources :companies, except: [:destroy, :show]
  post 'disable_company', to: 'companies#disable', as: 'disable_company'
  resources :profiles, except: [:destroy, :show]
  post 'disable_profile', to: 'profiles#disable', as: 'disable_profile'
  resources :documents
  post 'disable_document', to: 'documents#disable', as: 'disable_document'
  resources :document_categories
  resources :expiration_types
  
  get 'documents_profiles/:id/modal_disable', to: 'documents_profiles#modal_disable', as: 'modal_disable_document_profile'
  resources :documents_profiles, except: [:destroy, :show]
  post 'disable_document_profile', to: 'documents_profiles#disable', as: 'disable_document_profile'
  
  resources :people_profiles, except: [:destroy, :show]
  resources :vehicles_profiles, except: [:destroy, :show] 

  resources :assignments_profiles, except: [:index, :destroy]
  post 'disable_assignment_profile', to: 'assignments_profiles#disable', as: 'disable_assignment_profile'
  post 'reactive_profile_assignment_profile', to: 'assignments_profiles#reactive_profile', as: 'reactive_profile_assignment_profile'

  resources :assignments_documents, except: [:index, :destroy]
  get 'assignments_documents/:id/modal_disable', to: 'assignments_documents#modal_disable', as: 'modal_disable_assignments_documents'
  post 'disable_assignments_documents', to: 'assignments_documents#disable', as: 'disable_assignments_documents'

  get 'status_documentation/people'
  get 'status_documentation/vehicles'

  resources :document_renovations do 
    get 'show_files'
  end
  post 'disable_document_renovation', to: 'document_renovations#disable', as: 'disable_document_renovation'

  resources :reasons_to_disables, except: [:destroy, :show]
  post 'disable_reason', to: 'reasons_to_disables#disable', as: 'disable_reason'

  resources :reports, only: [:index] do
    get 'modal_fuel_report', on: :collection
    get 'people', on: :collection
    get 'people_documents', on: :collection
    post 'people_documents', on: :collection
    get 'matriz_vehicles', on: :collection
    get 'fuel', on: :collection
    get 'by_closure', on: :collection
  end

  namespace :reports do
    get 'document_expirations', to: 'vehicles#document_expirations'
    post 'document_expirations', to: 'vehicles#document_expirations'
    resources :vehicles, only: [:index]
    #   post 'disable_user', to: 'users#disable', as: 'disable_user'
    # resources :sessions, only: [:create]
    # get 'login', to: 'sessions#new', as: 'login'
    # get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/insurance.rb
# == Schema Information
#
# Table name: insurances
#
#  id          :bigint           not null, primary key
#  name        :string(255)      not null
#  description :string(255)
#  active      :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Insurance < ApplicationRecord
	has_many :vehicle_insurances
	has_many :vehicles, through: :vehicle_insurances
	
	
	accepts_nested_attributes_for :vehicle_insurances

	validates :name, presence: true, 
		uniqueness: { case_sensitive: false, message: "Ya existe una aseguradora registrada con este nombre" }

	scope :actives, -> { where(active: true) }

	def disable current_user
		ActiveRecord::Base.transaction do
			self.vehicle_insurances.each do |vehicle_insurance|
				vehicle_insurance.update( active: false )
				ActivityHistory.create( action: :disable, 
					description: "Seguro desvinculado al eliminar la aseguradora #{self.name}", 
	      	record: vehicle_insurance, date: Time.now, user: current_user )
			end
			self.update(active: false)
		end
	end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :set_insurance, only: %i[ show edit update ]

  def index
    @insurances = Insurance.actives
  end

  def show
  end

  def new
    @insurance = Insurance.new
    @title_modal = 'Registrar aseguradora'
    @vehicles = Vehicle.actives
  end

  def edit
    @title_modal = "Editando aseguradora #{@insurance.name}"
    @vehicles = Vehicle.actives
  end

  def create
    @insurance = Insurance.new(insurance_params)
    
    respond_to do |format|
      activity_history = ActivityHistory.new( action: :create_record, description: "Se registro la aseguradora #{@insurance.name}", 
      record: @insurance, date: Time.now, user: current_user )
      if @insurance.save
        format.json { render json: { status: 'success', msg: 'Aseguradora registrada.' }, status: :created }
      else
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @insurance.update(insurance_params)
        format.json { render json: { status: 'success', msg: 'Datos actualizados' }, status: :ok }
        format.html { redirect_to insurance_url(@insurance), notice: "Insurance was successfully updated." }
      else
        format.json { render json: @insurance.errors, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def disable
    insurance = Insurance.find(params[:insurance_id])
    activity_history = ActivityHistory.new( action: :disable, description: "El usuario #{current_user.username} elimino la aseguradora #{insurance.name}", 
      record: insurance, date: Time.now, user: current_user )
    if insurance.disable( current_user ) && activity_history.save
      render json: { status: 'success', msg: 'Aseguradora eliminada' }, status: :ok
    else
      render json: { status: 'error', msg: 'Ocurrio un error al realizar la operación' }, status: :unprocessable_entity
    end

    rescue => e
      @response = e.message.split(':')
      render json: { @response[0] => @response[1] }, status: 402
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_insurance
      @insurance = Insurance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def insurance_params
      params.require(:insurance).permit(:name, :description, :active, 
        vehicle_insurances_attributes: [:id, :vehicle_id, :policy, :start_date, :end_date])
    end
end

app/views/insurances/_form.html.erb
<%= form_with(model: @insurance, id: 'form-insurance', multipart: true, class: 'needs-validation g-brd-around g-brd-gray-light-v4 g-pa-10 g-mb-10') do |form| %>
  <div class="form-group row">
    <%= form.label :name, 'Nombre: ', class: 'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6">
      <%= form.text_field :name, class: 'form-control', required:true %>
      <small class="invalid-feedback company_name"></small>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :description, 'Descripción:', class: 'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6">
      <%= form.text_area :description, class: 'form-control u-textarea-expandable g-resize-none', rows: 3 %>
    </div>
  </div>

  <hr>
  <p>Asignar vehiculo a la aseguradora: </p>
  <div class="form-group row">
    <div class="col-2">
      <div class="col-12">
        Vehiculo:
      </div>
      <div class="col-12">
        <%= form.select(:vehicle_id, @vehicles.collect {|v| [v.code, v.id]}, { include_blank: true},
                      class: 'form-control select-vehicle-insurance') %>
        <small class="form-control-feedback text-danger vehicle_insurance"></small>
      </div>
    </div>
    <div class="col-2">
      <div class="col-12">
        Poliza:
      </div>
      <div class="col-12">
        <%= form.text_field :policy, class: 'form-control' %>
        <small class="form-control-feedback text-danger vehicle_insurance_policy"></small>
      </div>
    </div>
    <div class="col-2">
      <div class="col-12">
        Fecha inicio:
      </div>
      <div class="col-12">
        <%= form.date_field :start_date, class: 'form-control' %>
        <small class="form-control-feedback text-danger vehicle_insurance_start_date"></small>
      </div>
    </div>
    <div class="col-2">
      <div class="col-12">
        Fecha vencimiento:
      </div>
      <div class="col-12">
        <%= form.date_field :end_date, class: 'form-control' %>
        <small class="form-control-feedback text-danger vehicle_insurance_endt_date"></small>
      </div>
    </div>
    <div class="col-1">
      <div class="col-12">
        Archivos
      </div>
      <div class="col-12">
        <label class="u-file-attach-v2 g-color-gray-dark-v5 mb-0">
          <%= form.file_field :file, multiple: true%>
          <i class="icon-cloud-upload g-font-size-16 g-pos-rel"></i>
          <small class="form-control-feedback text-danger insurance_file"></small>
        </label>
      </div>
    </div>
    <div class="col-2">
      <button id='add_vehicle_insurance' type="button" class="btn u-btn-purple"><i class="fa fa-plus"></i></button>
    </div>
  </div>

  <table class="table table-sm table-hover col-10 mt-4 mb-4">
    <thead class="thead-light"> 
      <tr>
        <th> Vehiculo </th>
        <th> Poliza </th>
        <th> Fecha inicio </th>
        <th> Fecha vencimiento </th>
      </tr>
      <tbody id="vehicle_insurance">
        <% @insurance.vehicle_insurances.each do |data| %>
          <tr>
            <td> <%= data.vehicle.code %> </td>
            <td> <%= data.policy %> </td>
            <td> <%= data.start_date %> </td>
            <td> <%= data.end_date %> </td>
          </tr>
        <% end %>
      </tbody>
    </thead>
  </table>
  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-primary mr-2' %>
    <button type="button" class="btn u-btn-red" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/insurances/edit.html.erb
<h1>Editing Insurance</h1>

<%= render 'form', insurance: @insurance %>

<%= link_to 'Show', @insurance %> |
<%= link_to 'Back', insurances_path %>

app/views/insurances/edit.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'xl', content: 'form' } ) %>")

$('.select-vehicle-insurance').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione vehiculo a agregar" });

$("#modal").modal('show')


document.getElementById('add_vehicle_insurance').addEventListener('click', (e) => {
  let vehicle_selected = $("#insurance_vehicle_id option:selected")
  let policy = document.querySelector('#insurance_policy').value
  let start_date = document.querySelector('#insurance_start_date').value
  let end_date = document.querySelector('#insurance_end_date').value
  if (vehicle_selected.val() != '' && start_date.value != '' && end_date.value != '' ) {
    document.getElementById('vehicle_insurance').innerHTML += `
        <tr class='vehicle_insurance_body'>
          <td id='td_vehicle_id' data-value=${vehicle_selected.val()}>${vehicle_selected.text()}</td>
          <td id='td_policy' data-value=${policy}>${policy}</td>
          <td id='td_start_date' data-value=${start_date}>${ formatDateAR( start_date ) }</td>
          <td id='td_end_date' data-value=${end_date}>${ formatDateAR( end_date ) }</td>
        </tr>
      `
  }
})

document.getElementById('form-insurance').addEventListener('submit', (e) => {
  e.preventDefault()
  e.stopPropagation()
  console.log(e.target.action)
  let form = new FormData()
  let vehicle_insurance_list = document.getElementsByClassName('vehicle_insurance_body')
  let vehicle_index = 1
  form.append( `insurance[name]`, document.querySelector('#insurance_name').value )
  form.append( `insurance[description]`, document.querySelector('#insurance_description').value )
  for (let data of vehicle_insurance_list) {
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][vehicle_id]`, data.querySelector('#td_vehicle_id').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][policy]`, data.querySelector('#td_policy').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][start_date]`, data.querySelector('#td_start_date').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][end_date]`, data.querySelector('#td_end_date').dataset.value )
    vehicle_index++
  }

  fetch(e.target.action, {
      method: 'PATCH',
      headers: {           
        'X-CSRF-Token': document.getElementsByName('csrf-token')[0].content,
      },
      body: form
    })
    .then( response => response.json() )
    .then( response => {
      if (response.status === 'success') {
        noty_alert(response.status, response.msg)
        insurances_table.ajax.reload(null,false)
        $("#modal").modal('hide')
      }
    } )
    .catch( error => noty_alert('error', 'Ocurrio un error, no se pudo registrar la venta') )
})

app/views/insurances/index.html.erb
<h1>Aseguradoras</h1>
<%= link_to "<i class='fa fa-plus'></i> Registrar aseguradora".html_safe, new_insurance_path(),remote: true, data: { toggle: :modal, target: '#modal' }, 
  class: 'btn u-btn-outline-indigo u-btn-hover-v1-2 mb-2' %>

<%= render( partial: 'shared/table', 
            locals: { table_id: 'insurances', 
                      color: 'blue', 
                      icon: 'fa-shield',
                      title: "Aseguradoras registradas", 
                      col_names: [ 'Aseguradora', 'Descripcion', 'Acciones' ] }) %>
<!-- Modal para eliminar insurance -->
<div class="modal fade" id="modal-disable-insurance" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de dar de baja esta aseguradora ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: disable_insurance_path, id: 'form-disable-insurance') do |form| %>
          <%= form.hidden_field :insurance_id %>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" data-dismiss="modal" class="btn u-btn-teal g-mr-10"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar insurance -->

app/views/insurances/new.html.erb
<h1>New Insurance</h1>

<%= render 'form', insurance: @insurance %>

<%= link_to 'Back', insurances_path %>

app/views/insurances/new.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'xl', content: 'form' } ) %>")

$('.select-vehicle-insurance').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione vehiculo a agregar" });

$("#modal").modal('show')

document.getElementById('add_vehicle_insurance').addEventListener('click', (e) => {
  let vehicle_selected = $("#insurance_vehicle_id option:selected")
  let policy = document.querySelector('#insurance_policy').value
  let start_date = document.querySelector('#insurance_start_date').value
  let end_date = document.querySelector('#insurance_end_date').value
  if (vehicle_selected.val() != '' && start_date.value != '' && end_date.value != '' ) {
    document.getElementById('vehicle_insurance').innerHTML += `
        <tr class='vehicle_insurance_body'>
          <td id='td_vehicle_id' data-value=${vehicle_selected.val()}>${vehicle_selected.text()}</td>
          <td id='td_policy' data-value=${policy}>${policy}</td>
          <td id='td_start_date' data-value=${start_date}>${ formatDateAR( start_date ) }</td>
          <td id='td_end_date' data-value=${end_date}>${ formatDateAR( end_date ) }</td>
        </tr>
      `
  }
})

document.getElementById('form-insurance').addEventListener('submit', (e) => {
  e.preventDefault()
  e.stopPropagation()
  let form = new FormData()
  let vehicle_insurance_list = document.getElementsByClassName('vehicle_insurance_body')
  let vehicle_index = 1
  form.append( `insurance[name]`, document.querySelector('#insurance_name').value )
  form.append( `insurance[description]`, document.querySelector('#insurance_description').value )
  for (let data of vehicle_insurance_list) {
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][vehicle_id]`, data.querySelector('#td_vehicle_id').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][policy]`, data.querySelector('#td_policy').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][start_date]`, data.querySelector('#td_start_date').dataset.value )
    form.append( `insurance[vehicle_insurances_attributes][${vehicle_index}][end_date]`, data.querySelector('#td_end_date').dataset.value )
    vehicle_index++
  }

  fetch('/insurances/', {
      method: 'POST',
      headers: {           
        'X-CSRF-Token': document.getElementsByName('csrf-token')[0].content,
      },
      body: form
    })
    .then( response => response.json() )
    .then( response => {
      if (response.status === 'success') {
        noty_alert(response.status, response.msg)
        insurances_table.ajax.reload(null,false)
        $("#modal").modal('hide')
      }
    } )
    .catch( error => noty_alert('error', 'Ocurrio un error') )
})

app/views/insurances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @insurance.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @insurance.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @insurance.active %>
</p>

<%= link_to 'Edit', edit_insurance_path(@insurance) %> |
<%= link_to 'Back', insurances_path %>