config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"
  resources :vehicle_services
  resources :closures, only: [:index,:new,:create] do 
    get 'show_tickets', on: :collection
    get 'modal_send_report', on: :member
    post 'set_was_send', on: :member
  end
  resources :ticket_books do 
    get 'get_tickets', on: :member
    get 'modal_closed', on: :member
    put 'set_closed', on: :member
    post "disable", on: :collection
  end
  resources :tickets, except: [:destroy] do
    get "modal_change_status", on: :member
    post "change_status", on: :member
    get "modal_detail_disable", on: :member
  end
  resources :fuel_suppliers
  resources :fuel_to_vehicles do
    get 'import_excel', on: :collection
  end
  resources :fuel_loads
  root 'main#welcome'
  get 'main/welcome'

  resources :people_clothes, only: [:index, :show,:new, :create, :edit, :update] do 
    post "disable", on: :collection
  end
  post 'disable_people_clothe', to: 'people_clothes#disable', as: 'disable_people_clothe'
  resources :clothes, only: [:index, :new, :create, :edit, :update]
  post 'disable_clothe', to: 'clothes#disable', as: 'disable_clothe'
  resources :clothing_packages
  post 'disable_clothing_package', to: 'clothing_packages#disable', as: 'disable_clothing_package'
  post 'disable_clothes_pack', to: "clothes_packs#disable", as: "disable_clothes_pack" # elimino una prenda de ropa de un package
  resources :insurances
  resources :vehicle_insurances do 
    get 'show_files', on: :collection
  end
  post 'disable_insurance', to: 'insurances#disable', as: 'disable_insurance'

  resources :vehicles, except: [:destroy] do 
    get 'show_images', on: :member
    get 'get_images', on: :member
    get 'show_vehicle_history', on: :member
    get 'modal_enable_vehicle', on: :member
    post :delete_image_attachment, on: :collection
    get 'status_mileage_for_service', on: :member
    get 'admin_units_load', on: :collection
  end
  post 'disable_vehicle', to: 'vehicles#disable', as: 'disable_vehicle'
  get 'inactives_vehicles', to: 'vehicles#inactives', as: 'inactives_vehicles'

  get 'vehicles/:id/show_vehicle_history', to: 'vehicles#show_vehicle_history', as: 'show_vehicle_history'
  get 'vehicles/:id/modal_enable_vehicle', to: 'vehicles#modal_enable_vehicle', as: 'modal_enable_vehicle'
  post 'vehicles/enable_vehicle', to: 'vehicles#enable_vehicle', as: 'enable_vehicle'
  resources :vehicle_locations
  
  resources :vehicle_models
  post 'disable_vehicle_model', to: 'vehicle_models#disable', as: 'disable_vehicle_model'
  
  resources :vehicle_brands, except: [:destroy]
  post 'disable_vehicle_brand', to: 'vehicle_brands#disable', as: 'disable_vehicle_brand'
  
  resources :vehicle_types, except: [:destroy]
  post 'disable_vehicle_type', to: 'vehicle_types#disable', as: 'disable_vehicle_type'
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create, :edit, :update]
      post 'disable_user', to: 'users#disable', as: 'disable_user'
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
  
  get 'person_dato_disponible', to: 'people#dato_disponible', as: 'person_dato_disponible'
  get '/people/:id/upload_person_file/:file', to: 'people#upload_person_file', as: 'upload_person_file'
  resources :people, except: [:destroy] do 
    get "permission_fuel_load", on: :collection
    post 'set_permission', on: :member
  end
  post 'disable_person', to: 'people#disable', as: 'disable_person'
  get 'inactive_people', to: 'people#inactives', as: 'inactive_people'
  get 'people/:id/show_person_history', to: 'people#show_person_history', as: 'show_person_history'
  get 'people/:id/modal_enable_person', to: 'people#modal_enable_person', as: 'modal_enable_person'
  post 'people/enable_person', to: 'people#enable_person', as: 'enable_person'
  resources :companies, except: [:destroy, :show]
  post 'disable_company', to: 'companies#disable', as: 'disable_company'
  resources :profiles, except: [:destroy, :show]
  post 'disable_profile', to: 'profiles#disable', as: 'disable_profile'
  resources :documents
  post 'disable_document', to: 'documents#disable', as: 'disable_document'
  resources :document_categories
  resources :expiration_types
  
  get 'documents_profiles/:id/modal_disable', to: 'documents_profiles#modal_disable', as: 'modal_disable_document_profile'
  resources :documents_profiles, except: [:destroy, :show]
  post 'disable_document_profile', to: 'documents_profiles#disable', as: 'disable_document_profile'
  
  resources :people_profiles, except: [:destroy, :show]
  resources :vehicles_profiles, except: [:destroy, :show] 

  resources :assignments_profiles, except: [:index, :destroy]
  post 'disable_assignment_profile', to: 'assignments_profiles#disable', as: 'disable_assignment_profile'
  post 'reactive_profile_assignment_profile', to: 'assignments_profiles#reactive_profile', as: 'reactive_profile_assignment_profile'

  resources :assignments_documents, except: [:index, :destroy]
  get 'assignments_documents/:id/modal_disable', to: 'assignments_documents#modal_disable', as: 'modal_disable_assignments_documents'
  post 'disable_assignments_documents', to: 'assignments_documents#disable', as: 'disable_assignments_documents'

  get 'status_documentation/people'
  get 'status_documentation/vehicles'

  resources :document_renovations do 
    get 'show_files'
  end
  post 'disable_document_renovation', to: 'document_renovations#disable', as: 'disable_document_renovation'

  resources :reasons_to_disables, except: [:destroy, :show]
  post 'disable_reason', to: 'reasons_to_disables#disable', as: 'disable_reason'

  resources :reports, only: [:index] do
    get 'modal_fuel_report', on: :collection
    get 'people', on: :collection
    get 'people_documents', on: :collection
    post 'people_documents', on: :collection
    get 'matriz_vehicles', on: :collection
    get 'fuel', on: :collection
    get 'by_closure', on: :collection
  end

  namespace :reports do
    get 'document_expirations', to: 'vehicles#document_expirations'
    post 'document_expirations', to: 'vehicles#document_expirations'
    resources :vehicles, only: [:index]
    #   post 'disable_user', to: 'users#disable', as: 'disable_user'
    # resources :sessions, only: [:create]
    # get 'login', to: 'sessions#new', as: 'login'
    # get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id                      :bigint           not null, primary key
#  d_type                  :integer          not null
#  name                    :string(255)      not null
#  description             :string(255)
#  expires                 :boolean          default(FALSE)
#  days_of_validity        :integer          default(0)
#  allow_modify_expiration :boolean          default(FALSE)
#  observations            :text(65535)
#  renewal_methodology     :text(65535)
#  monthly_summary         :boolean          default(TRUE)
#  start_date              :date
#  end_date                :date
#  active                  :boolean          default(TRUE)
#  document_category_id    :bigint
#  expiration_type_id      :bigint
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  apply_to_all            :boolean          default(FALSE)
#
class Document < ApplicationRecord
	# la expiracion la manejo con una tabla expiration_type, en base a esa tabla sacamos cuantos dias vale el documento
	# tengo explicito un campo de dias xq si eligen "personalizado" deben seterar la cantidad de dias a mano
	# en caso de actualizar los dias de cada tipo de expiracion se va a actualizar en todos los documentos
	belongs_to :document_category
	belongs_to :expiration_type, optional: true

	validates :name, presence: true, 
		uniqueness: { scope: :d_type, case_sensitive: false, message: "Este documento ya se encuentra registrado" }
	validates :d_type, presence: true

	validates :days_of_validity, numericality: { only_integer: true, message: 'Debe ingresar un número.' },
		presence: { message: 'Debe ingresar los días de duración del atributo.' }, if: :document_expire?

	validates :expiration_type_id, presence: { message: 'Seleccione un periodo de vencimiento'}, if: :document_expire?

	validates :end_date, presence: { message: 'Para dar de baja un documento se necesita ingresar la fecha de finalización.'}, if: :document_inactive?

	before_create :set_data_if_no_expire

	after_save :check_apply_to_all

	enum d_type: {
		people: 1, 
		vehicles: 2
	}

	scope :actives, -> { where(active: true) }

	private 

	def set_data_if_no_expire
		if !self.expires?
			expiration_type = ExpirationType.where(active: false, name: 'No vence').first
			self.expiration_type_id = expiration_type.id
		end
	end

	def document_expire?
		self.expires?
	end

	def document_inactive?
		!self.active
	end

	def check_apply_to_all
		if self.apply_to_all
			set_document_to_all
		end
	end

	def set_document_to_all
		if self.d_type == 'people'
			assignateds = Person.actives
		else
			assignateds = Vehicle.actives
		end
		assignateds.each do |assignated|
			assignment_document = AssignmentsDocument.where( document: self, assignated: assignated ).first 
			if assignment_document.blank?
				assignated.assignments_documents.create( document: self, start_date: self.start_date )
			end
		end
	end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  def index
    @documents = Document.where( d_type: params[:d_type]).all
    @document_type = ( params[:d_type] == 'people' ) ? 'personal' : 'vehiculos'
  end

  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
    @expiration_types = ExpirationType.actives
    @categories = DocumentCategory.actives
    @title_modal = 'Registro de documento'
  end

  def edit
    @expiration_types = ExpirationType.actives
    @categories = DocumentCategory.actives
    @title_modal = "Editando el documento: #{@document.name}"
  end

  def create
    @document = Document.new(document_params)
    respond_to do |format|
      if @document.save
        format.json { render json: { status: 'success', msg: 'Documento creado con éxito.' }, status: :created }
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
      else
        format.json { render json: @document.errors, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @document.update(document_params)
        format.json { render json: { status: 'success', msg: 'Documento creado con éxito.' }, status: :ok }
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
      else
        format.json { render json: @document.errors, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def disable
    @document = Document.find(params[:document_id])
    respond_to do |format|
      if @document.update(active:false, end_date: params[:end_date])
        format.json { render json: { status: 'success', msg: 'Documento eliminado' }, status: :ok }
      else
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end

    rescue => e
      @response = e.message.split(':')
      render json: { @response[0] => @response[1] }, status: 402
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:name, :description, :expires, :days_of_validity, :d_type, 
        :allow_modify_expiration, :observations, :renewal_methodology, :start_date, :end_date, :monthly_summary, :active,
        :document_category_id, 
        :expiration_type_id, :apply_to_all)
    end
end

app/views/documents/_form.html.erb
<%= form_with(model: @document,id: 'form-document', class: 'needs-validation g-brd-around g-brd-gray-light-v4 g-pa-10 g-mb-10') do |form| %>
  <%= form.hidden_field :d_type, value: params[:d_type] %>
  <div class="form-group row">
    <%= form.label :name, 'Nombre (*) ', class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6">
      <%= form.text_field :name, class: 'form-control', required:true %>
      <small class="form-control-feedback text-danger document_name"></small>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, 'Descripción ', class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6 ">
      <%= form.text_area :description, class: 'form-control u-textarea-expandable g-resize-none', rows: 3 %>
      <small class="form-control-feedback text-danger document_description"></small>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :document_category_id, 'Categoría (*)', class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-8 col-lg-6">
      <%= form.select(:document_category_id, @categories.collect {|c| [c.name, c.id]}, { include_blank: true},
                      class: 'form-control select-2-document-category', required: true) %>
      <small class="form-control-feedback text-danger document_document_category_id document_document_category"></small>
    </div>
  </div>

  <div class="form-group">
    <label class="form-check-inline u-check g-pl-25">
      <%= form.check_box :apply_to_all, class: 'g-hidden-xs-up g-pos-abs g-top-0 g-left-0' %>
      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
        <i class="fa" data-check-icon="&#xf00c"></i>
      </div>
      Aplica a todos
    </label>
  </div>

  <div class="form-group">
    <label class="form-check-inline u-check g-pl-25">
      <%= form.check_box :expires, class: 'g-hidden-xs-up g-pos-abs g-top-0 g-left-0' %>
      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
        <i class="fa" data-check-icon="&#xf00c"></i>
      </div>
      Tiene vencimiento
    </label>
  </div>

 <div class="form-group row" style="display: none">
    <%= form.label :expiration_type_id, 'Periodo de vencimiento' ,class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-8 col-lg-6">
      <%= form.select(:expiration_type_id, @expiration_types.collect { |e| [e.name, e.id, data: { days: e.days }] }, { include_blank: true},
                      onchange: 'check_expiration_type()',
                      class: 'form-control select-2-document-expiration') %>
    <small class="form-control-feedback text-danger document_expiration_type_id"></small>
    </div>
 </div>

  <div class="form-group row" style="display: none">
    <%= form.label :days_of_validity, 'Valido durante',class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6 ">
      <%= form.text_field :days_of_validity, class: 'form-control', placeholder: 'Cada cuantos días hay que renovar el atributo' %>
      <small class="form-control-feedback text-danger document_days_of_validity"></small>
    </div>
  </div>

  <div class="form-group" style="display: none">
    <label class="form-check-inline u-check g-pl-25">
      <%= form.check_box :allow_modify_expiration, class: 'g-hidden-xs-up g-pos-abs g-top-0 g-left-0' %>
      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
        <i class="fa" data-check-icon="&#xf00c"></i>
      </div>
      Permite modificar proximo vencimiento  
    </label>
  </div>

  <div class="form-group row">
    <%= form.label :observations, 'Observaciones:', class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6 ">
      <%= form.text_area :observations, class: 'form-control u-textarea-expandable g-resize-none', rows: 3 %>
      <small class="form-control-feedback text-danger document_observations"></small>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :renewal_methodology,'Metodología de renovación', class:'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6 ">
      <%= form.text_area :renewal_methodology, class: 'form-control u-textarea-expandable g-resize-none', rows: 3 %>
      <small class="form-control-feedback text-danger document_renewal_methodology"></small>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :start_date, 'Inicio vigencia' ,class:'col-form-label col-sm-3 col-md-4', title: 'Cuando se empezo a pedir este documento' %>
    <div class="col-9 col-md-6 input-group g-brd-primary--focus">
      <%= form.date_field :start_date, class: 'form-control' %>
      <small class="form-control-feedback text-danger document_start_date"></small>
    </div>
  </div>

  <div class="form-group">
    <label class="form-check-inline u-check g-pl-25">
      <%= form.check_box :monthly_summary, class: 'g-hidden-xs-up g-pos-abs g-top-0 g-left-0' %>
      <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
        <i class="fa" data-check-icon="&#xf00c"></i>
      </div>
      Presenta en resumen mensual
    </label>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-primary mr-2' %>
    <button type="button" class="btn u-btn-red" data-dismiss="modal">Cerrar</button>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/edit.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'form' } ) %>")

$('.select-2-document-category').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione categoría (*)" });
$('.select-2-document-expiration').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione período de vencimiento (*)" });

document.querySelector('#form-document #document_d_type').value = document.getElementById('d_type').value

check_expiration_type()

documents.check_is_expire( document.getElementById('document_expires') )

$("#modal").modal('show')

document.getElementById('document_expires').addEventListener('click', (e) => {
  documents.check_is_expire(e.target)
})

function check_expiration_type(){
  let expiration_type = document.getElementById('document_expiration_type_id')
  let days = expiration_type.options[expiration_type.selectedIndex].dataset.days
  if (days == 0) {
    document.getElementById('document_days_of_validity').value = <%= @document.days_of_validity %>
    document.getElementById('document_days_of_validity').parentNode.parentNode.style.display = ''
  } else {
    document.getElementById('document_days_of_validity').parentNode.parentNode.style.display = 'none'
    document.getElementById('document_days_of_validity').value = days
  }
}

$("#form-document").on("ajax:success", function(event) {
    documents_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
	let msg = JSON.parse( event.detail[2].response )
	set_input_status_form('form-document', 'document', msg)
})

app/views/documents/index.html.erb
<h1>Documentos de <%= @document_type %></h1>
<%= link_to "<i class='fa fa-plus'></i> Registrar documento".html_safe, new_document_path( d_type: params[:d_type] ),remote: true, 
            class: 'btn u-btn-outline-indigo u-btn-hover-v1-2 mb-2' %>

<%= render( partial: 'shared/table', 
            locals: { table_id: 'documents', 
                      color: 'purple', 
                      icon: 'fa-folder-open-o',
                      title: "Documentos registrados", 
                      col_names: [ 'Nombre','Descripción','Categoría','Tiene venc.', 'Tipo venc.', 'Periodo venc.', 'Permite editar prox. venc.', 'Observaciones', 'Metodología de renovación', 'Presenta resumen mensual','Inicio vigencia', 'Fin vigencia' , 'Aplica a todos','Estado','Acciones' ] }) %>

<!-- Modal para eliminar document -->
<div class="modal fade" id="modal-disable-document" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de dar de baja este documento ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: disable_document_path, id: 'form-disable-document') do |form| %>
          <%= form.hidden_field :document_id %>
          <div class="form-group g-mb-10">
            <%= form.label :end_date, 'Fecha finalización vigencia:', class: "col-form-label" %>
            <%= form.date_field :end_date, class: "form-control u-form-control"%>
            <small class="form-control-feedback text-danger end_date"></small>
          </div>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" data-dismiss="modal" class="btn u-btn-teal g-mr-10"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar document -->

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/new.js.erb
$("#modal").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'form' } ) %>")

$('.select-2-document-category').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione categoría (*)" });
$('.select-2-document-expiration').select2({ width: '100%',theme: "bootstrap4", placeholder: "Seleccione período de vencimiento (*)" });

setInputDate('#form-document #document_start_date')

$("#modal").modal('show')

document.getElementById('document_expires').addEventListener('click', (e) => {
  if (e.target.checked) {
    document.getElementById('document_expiration_type_id').parentNode.parentNode.style.display = ''
    document.getElementById('document_allow_modify_expiration').parentNode.parentNode.style.display = ''
  } else {
    document.getElementById('document_expiration_type_id').parentNode.parentNode.style.display = 'none'
    document.getElementById('document_allow_modify_expiration').parentNode.parentNode.style.display = 'none'
  }
})

function check_expiration_type(){
  let expiration_type = document.getElementById('document_expiration_type_id')
  let days = expiration_type.options[expiration_type.selectedIndex].dataset.days
  if (days == 0) {
    document.getElementById('document_days_of_validity').value = ''
    document.getElementById('document_days_of_validity').parentNode.parentNode.style.display = ''
  } else {
    document.getElementById('document_days_of_validity').parentNode.parentNode.style.display = 'none'
    document.getElementById('document_days_of_validity').value = days
  }
}

$("#form-document").on("ajax:success", function(event) {
    documents_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#modal").modal('hide')
  }).on("ajax:error", function(event) {
	let msg = JSON.parse( event.detail[2].response )
	set_input_status_form('form-document', 'document', msg)
})

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @document.description %>
</p>

<p>
  <strong>Expires:</strong>
  <%= @document.expires %>
</p>

<p>
  <strong>Expiration type:</strong>
  <%= @document.expiration_type %>
</p>

<p>
  <strong>Days of validity:</strong>
  <%= @document.days_of_validity %>
</p>

<p>
  <strong>Allow modify expiration:</strong>
  <%= @document.allow_modify_expiration %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @document.observations %>
</p>

<p>
  <strong>Renewal methodology:</strong>
  <%= @document.renewal_methodology %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @document.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @document.end_date %>
</p>

<p>
  <strong>Active:</strong>
  <%= @document.active %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>