config/routes.rb
Rails.application.routes.draw do
  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"
  resources :vehicle_services
  resources :closures, only: [:index,:new,:create] do 
    get 'show_tickets', on: :collection
    get 'modal_send_report', on: :member
    post 'set_was_send', on: :member
  end
  resources :ticket_books do 
    get 'get_tickets', on: :member
    get 'modal_closed', on: :member
    put 'set_closed', on: :member
    post "disable", on: :collection
  end
  resources :tickets, except: [:destroy] do
    get "modal_change_status", on: :member
    post "change_status", on: :member
    get "modal_detail_disable", on: :member
  end
  resources :fuel_suppliers
  resources :fuel_to_vehicles do
    get 'import_excel', on: :collection
  end
  resources :fuel_loads
  root 'main#welcome'
  get 'main/welcome'

  resources :people_clothes, only: [:index, :show,:new, :create, :edit, :update] do 
    post "disable", on: :collection
  end
  post 'disable_people_clothe', to: 'people_clothes#disable', as: 'disable_people_clothe'
  resources :clothes, only: [:index, :new, :create, :edit, :update]
  post 'disable_clothe', to: 'clothes#disable', as: 'disable_clothe'
  resources :clothing_packages
  post 'disable_clothing_package', to: 'clothing_packages#disable', as: 'disable_clothing_package'
  post 'disable_clothes_pack', to: "clothes_packs#disable", as: "disable_clothes_pack" # elimino una prenda de ropa de un package
  resources :insurances
  resources :vehicle_insurances do 
    get 'show_files', on: :collection
  end
  post 'disable_insurance', to: 'insurances#disable', as: 'disable_insurance'

  resources :vehicles, except: [:destroy] do 
    get 'show_images', on: :member
    get 'get_images', on: :member
    get 'show_vehicle_history', on: :member
    get 'modal_enable_vehicle', on: :member
    post :delete_image_attachment, on: :collection
    get 'status_mileage_for_service', on: :member
    get 'admin_units_load', on: :collection
  end
  post 'disable_vehicle', to: 'vehicles#disable', as: 'disable_vehicle'
  get 'inactives_vehicles', to: 'vehicles#inactives', as: 'inactives_vehicles'

  get 'vehicles/:id/show_vehicle_history', to: 'vehicles#show_vehicle_history', as: 'show_vehicle_history'
  get 'vehicles/:id/modal_enable_vehicle', to: 'vehicles#modal_enable_vehicle', as: 'modal_enable_vehicle'
  post 'vehicles/enable_vehicle', to: 'vehicles#enable_vehicle', as: 'enable_vehicle'
  resources :vehicle_locations
  
  resources :vehicle_models
  post 'disable_vehicle_model', to: 'vehicle_models#disable', as: 'disable_vehicle_model'
  
  resources :vehicle_brands, except: [:destroy]
  post 'disable_vehicle_brand', to: 'vehicle_brands#disable', as: 'disable_vehicle_brand'
  
  resources :vehicle_types, except: [:destroy]
  post 'disable_vehicle_type', to: 'vehicle_types#disable', as: 'disable_vehicle_type'
  
  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create, :edit, :update]
      post 'disable_user', to: 'users#disable', as: 'disable_user'
    resources :sessions, only: [:create]
    get 'login', to: 'sessions#new', as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
  end
  
  get 'person_dato_disponible', to: 'people#dato_disponible', as: 'person_dato_disponible'
  get '/people/:id/upload_person_file/:file', to: 'people#upload_person_file', as: 'upload_person_file'
  resources :people, except: [:destroy] do 
    get "permission_fuel_load", on: :collection
    post 'set_permission', on: :member
  end
  post 'disable_person', to: 'people#disable', as: 'disable_person'
  get 'inactive_people', to: 'people#inactives', as: 'inactive_people'
  get 'people/:id/show_person_history', to: 'people#show_person_history', as: 'show_person_history'
  get 'people/:id/modal_enable_person', to: 'people#modal_enable_person', as: 'modal_enable_person'
  post 'people/enable_person', to: 'people#enable_person', as: 'enable_person'
  resources :companies, except: [:destroy, :show]
  post 'disable_company', to: 'companies#disable', as: 'disable_company'
  resources :profiles, except: [:destroy, :show]
  post 'disable_profile', to: 'profiles#disable', as: 'disable_profile'
  resources :documents
  post 'disable_document', to: 'documents#disable', as: 'disable_document'
  resources :document_categories
  resources :expiration_types
  
  get 'documents_profiles/:id/modal_disable', to: 'documents_profiles#modal_disable', as: 'modal_disable_document_profile'
  resources :documents_profiles, except: [:destroy, :show]
  post 'disable_document_profile', to: 'documents_profiles#disable', as: 'disable_document_profile'
  
  resources :people_profiles, except: [:destroy, :show]
  resources :vehicles_profiles, except: [:destroy, :show] 

  resources :assignments_profiles, except: [:index, :destroy]
  post 'disable_assignment_profile', to: 'assignments_profiles#disable', as: 'disable_assignment_profile'
  post 'reactive_profile_assignment_profile', to: 'assignments_profiles#reactive_profile', as: 'reactive_profile_assignment_profile'

  resources :assignments_documents, except: [:index, :destroy]
  get 'assignments_documents/:id/modal_disable', to: 'assignments_documents#modal_disable', as: 'modal_disable_assignments_documents'
  post 'disable_assignments_documents', to: 'assignments_documents#disable', as: 'disable_assignments_documents'

  get 'status_documentation/people'
  get 'status_documentation/vehicles'

  resources :document_renovations do 
    get 'show_files'
  end
  post 'disable_document_renovation', to: 'document_renovations#disable', as: 'disable_document_renovation'

  resources :reasons_to_disables, except: [:destroy, :show]
  post 'disable_reason', to: 'reasons_to_disables#disable', as: 'disable_reason'

  resources :reports, only: [:index] do
    get 'modal_fuel_report', on: :collection
    get 'people', on: :collection
    get 'people_documents', on: :collection
    post 'people_documents', on: :collection
    get 'matriz_vehicles', on: :collection
    get 'fuel', on: :collection
    get 'by_closure', on: :collection
  end

  namespace :reports do
    get 'document_expirations', to: 'vehicles#document_expirations'
    post 'document_expirations', to: 'vehicles#document_expirations'
    resources :vehicles, only: [:index]
    #   post 'disable_user', to: 'users#disable', as: 'disable_user'
    # resources :sessions, only: [:create]
    # get 'login', to: 'sessions#new', as: 'login'
    # get 'logout', to: 'sessions#destroy', as: 'logout'
  end
end

app/models/ticket_book.rb
# == Schema Information
#
# Table name: ticket_books
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  active     :boolean          default(TRUE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  completed  :boolean          default(FALSE)
#
class TicketBook < ApplicationRecord
	has_many :tickets, dependent: :destroy

	accepts_nested_attributes_for :tickets
	
	validates :name, 
		presence: true, 
		uniqueness: { case_sensitive: false, message: "Ya hay un talonario registrado con este nombre" }

	scope :actives, -> { where(active: true) }
	
	def used
		!self.tickets.where(used: :true).empty?
	end

	def is_completed?
		self.tickets.where(used: :false).empty?
	end

	def create_ticket_book number_from, number_until
		if number_from >= number_until
			errors.add(:base, 'El número de inicio debe ser menor al de fin')
		end
		ActiveRecord::Base.transaction do
			if !self.save
				return false
			end
			for n in number_from..number_until do
				ticket = Ticket.new( ticket_book: self, number: n )
				if !ticket.save
					errors.add(:base, 'Hay tickets que pertenecen a otro talonario')
				end
			end
		end
	end

	def check_is_completed
		if self.is_completed?
			self.update(completed: true) 
		else 
			self.update( completed: false )
		end
	end

	def set_closed
		tickets = self.tickets.where(used: false)
		tickets.destroy_all
		self.update(completed: true)
	end

	def ticket_range
		tickets = self.tickets.order(:number)
		if tickets.blank?
			"--"
		else
			"#{tickets.first.number} - #{tickets.last.number}"
		end
	end

	def disable
		tickets = self.tickets.where(used: true)
		if !tickets.blank?
			errors.add(:base, 'Hay tickets usados en este talonario') 
			return
		end
		self.destroy
	end

end

app/controllers/ticket_books_controller.rb
class TicketBooksController < ApplicationController
  before_action :set_ticket_book, only: %i[ show edit update destroy modal_closed set_closed]

  # GET /ticket_books or /ticket_books.json
  def index
    @title_modal = "Talonarios"
    @ticket_books = TicketBook.actives.includes(:tickets)
  end

  # GET /ticket_books/1 or /ticket_books/1.json
  def show
  end

  # GET /ticket_books/new
  def new
    @title_modal = "Registrar talonario"
    @ticket_book = TicketBook.new
    @start_tickets = 1
    @end_tickets = 10
  end

  # GET /ticket_books/1/edit
  def edit
    @start_tickets = @ticket_book.tickets.first.number
    @end_tickets = @ticket_book.tickets.last.number
  end

  # POST /ticket_books or /ticket_books.json
  def create
    @ticket_book = TicketBook.new(ticket_book_params)
    respond_to do |format|
      if @ticket_book.save
        format.json { render json: { status: 'success', msg: 'Talonario registrado' }, status: :created}
      else
        format.json { render json: { status: "error", msg: @ticket_book.errors }, status: :unprocessable_entity }
      end
    end
    rescue => e
      @response = e.message.split(':')
      render json: { @response[0] => @response[1] }, status: 402
  end

  # PATCH/PUT /ticket_books/1 or /ticket_books/1.json
  def update
    respond_to do |format|
      if @ticket_book.update(ticket_book_params)
        format.html { redirect_to ticket_book_url(@ticket_book), notice: "Ticket book was successfully updated." }
        format.json { render :show, status: :ok}
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket_book.errors, status: :unprocessable_entity }
      end
    end
  end

  def modal_closed
    pp @ticket_book
    @title_modal = "Cerrar talonario"
  end

  def set_closed
    respond_to do |format|
      if @ticket_book.set_closed
        format.json { render json: { status: 'success', msg: 'Talonario cerrado' }, status: :ok}
      else
        format.json { render json: @ticket_book.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_tickets
    ticket_book = TicketBook.find(params[:id])
    render json: { tickets: ticket_book.tickets.unused.actives.order(number: :asc) }
  end

  def disable
    ticket_book = TicketBook.find(params[:ticket_book_id])
    respond_to do |format|
      if ticket_book.disable
        format.json { render json: { status: 'success', msg: 'Talonario eliminado' }, status: :ok}
      else
        format.json { render json: { status: 'success', msg: ticket_book.errors }, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_book
      @ticket_book = TicketBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_book_params
      params.require(:ticket_book).permit(:name, :status, :active,
        tickets_attributes: [:id, :ticket_book_id, :number])
    end
end

app/views/ticket_books/_form.html.erb
<%= form_with(model: @ticket_book, id: 'ticket-book-form') do |form| %>

  <div class="form-group row">
    <%= form.label :name, 'Nombre: ', class: 'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6">
      <%= form.text_field :name, class: 'form-control', required:true, placeholder: 'Nombre del talonario' %>
      <small class="invalid-feedback ticket_book_name"></small>
    </div>
  </div>
  <div class="form-group row">
    <%= form.label :ticket_from, 'N° de tickets:', class: 'col-form-label col-sm-3 col-md-4' %>
    <div class="col-sm-9 col-md-6 row">
      <div class="col-6">
        <%= form.number_field :ticket_from, class: 'form-control', placeholder: 'Desde el n°', required: true, value: @start_tickets %>
        <small class="invalid-feedback ticket_book_ticket_from ticket_book_tickets"></small>
        <small class="invalid-feedback ticket_book_base"></small>
      </div>
      <div class="col-6">
        <%= form.number_field :ticket_until, class: 'form-control', placeholder: 'Hasta el n°', required: true, value: @end_tickets %>
        <small class="invalid-feedback ticket_book_ticket_until ticket_book_tickets"></small>
        <small class="invalid-feedback ticket_book_base"></small>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-primary mr-2' %>
    <button type="button" class="btn u-btn-red" data-dismiss="modal">Cerrar</button>
  </div>

<% end %>

app/views/ticket_books/_form_set_closed.html.erb
<%= form_with(url: set_closed_ticket_book_path(@ticket_book.id), id: 'ticket-book-form', method: 'PUT') do |form| %>
	<p>Al cerrar el talonario no se pueden agregar mas cargas a este talonario.</p>
  <div class="actions">
    <%= form.submit 'Guardar', class: 'btn u-btn-primary mr-2' %>
    <button type="button" class="btn u-btn-red" data-dismiss="modal">Cerrar</button>
  </div>

<% end %>

app/views/ticket_books/_index.html.erb
<div class="modal-dialog modal-xl" role="document">
  <div class="modal-content">
    <div class="modal-header g-brd-blue g-bg-blue">
      <h5 class="modal-title text-white"><strong><%= @title_modal%></strong></h5>
      <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= link_to "<i class='fa fa-plus'></i> Registrar talonario".html_safe, new_ticket_book_path(), remote: true,
          class: 'btn u-btn-outline-cyan u-btn-hover-v1-2 mb-2 mr-4' %>
      <%= render( partial: 'shared/table', 
            locals: { table_id: 'ticket_books', 
                      color: 'blue', 
                      icon: 'fa-book',
                      title: "Talonarios", 
                      col_names: [ 'Nombre', 'Desde - Hasta','Usado' ,'Completado', 'Acciones' ] }) %>
    </div>
  </div>
</div>

<!-- Modal para eliminar talonario -->
<div class="modal fade" id="modal-disable-ticket-book" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">¿ Esta seguro de dar de baja este talonario ?</h5>
        <button type="button" class="close" onclick="close_modal('modal-disable-ticket-book')">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: disable_ticket_books_path, id: 'form-disable-ticket-book') do |form| %>
          <%= form.hidden_field :ticket_book_id %>
          <%= form.submit 'Eliminar', class: 'btn u-btn-red g-mr-10' %>
          <button type="button" class="btn u-btn-teal g-mr-10" onclick="close_modal('modal-disable-ticket-book')"> Cerrar </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Fin modal eliminar talonario -->

app/views/ticket_books/edit.html.erb
<h1>Editing Ticket Book</h1>

<%= render 'form', ticket_book: @ticket_book %>

<%= link_to 'Show', @ticket_book %> |
<%= link_to 'Back', ticket_books_path %>

app/views/ticket_books/edit.js.erb
$("#ticket_book_create").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'form' } ) %>")

$("#ticket_book_create").modal('show')

$("#ticket-book-form").on("ajax:success", function(event) {
    ticket_books_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#ticket_book_create").modal('hide')
  }).on("ajax:error", function(event) {
	let msg = JSON.parse( event.detail[2].response )
	console.info(msg)
	set_input_status_form('ticket-book-form', 'ticket_book', msg)
})

app/views/ticket_books/index.js.erb
$("#ticket_books").html("<%= j (render partial: 'index' ) %>")

$(document).ready(function(){
	ticket_books_table = $("#ticket_books_table").DataTable({
    'ajax': `ticket_books`,
    'columns': [
    {'data': 'name'},
    {'data': 'ticket_range'},
    {'data': 'used'},
    {'data': 'completed'},
    {'data': 'actions'}
    ],
    'language': {'url': datatables_lang}
	})

  $("#form-disable-ticket-book").on("ajax:success", function(event) {
    ticket_books_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#modal-disable-ticket-book").modal('hide')
  }).on("ajax:error", function(event) {
    let msg = JSON.parse(event.detail[2].response)
    noty_alert("error", msg.msg.base[0])
  })

})

$("#ticket_books").modal('show')

app/views/ticket_books/modal_closed.js.erb
$("#ticket_book_create").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'form_set_closed', ticket_book_id: @ticket_book.id } ) %>")

$("#ticket_book_create").modal('show')

$("#ticket-book-form").on("ajax:success", function(event) {
    ticket_books_table.ajax.reload(null,false)
    let msg = JSON.parse(event.detail[2].response)
    noty_alert(msg.status, msg.msg)
    $("#ticket_book_create").modal('hide')
  }).on("ajax:error", function(event) {
	let msg = JSON.parse( event.detail[2].response )
	console.info(msg)
	set_input_status_form('ticket-book-form', 'ticket_book', msg)
})

app/views/ticket_books/new.html.erb
<h1>New Ticket Book</h1>

<%= render 'form', ticket_book: @ticket_book %>

<%= link_to 'Back', ticket_books_path %>

app/views/ticket_books/new.js.erb
$("#ticket_book_create").html("<%= j (render partial: 'shared/modal', locals:{ size: 'lg', content: 'form' } ) %>")

$("#ticket_book_create").modal('show')

// $("#ticket-book-form").on("ajax:success", function(event) {
//     ticket_books_table.ajax.reload(null,false)
//     let msg = JSON.parse(event.detail[2].response)
//     noty_alert(msg.status, msg.msg)
//     $("#ticket_book_create").modal('hide')
//   }).on("ajax:error", function(event) {
// 	let msg = JSON.parse( event.detail[2].response )
// 	console.info(msg)
// 	set_input_status_form('ticket-book-form', 'ticket_book', msg)
// })

document.getElementById("ticket-book-form").addEventListener("submit", (e) => {
  e.preventDefault()
  e.stopPropagation()
  let form = new FormData()
  const ticket_from = document.querySelector('#ticket_book_ticket_from').value
  const ticket_until = document.querySelector('#ticket_book_ticket_until').value

  if (ticket_from > ticket_until) {
    addClassInvalid( document.querySelector('#ticket_book_ticket_from') )
    addClassInvalid( document.querySelector('#ticket_book_ticket_until') )
    document.querySelector(`.ticket_book_ticket_from`).textContent = 'Rango inválido'
    return
  } else {
    addClassValid( document.querySelector('#ticket_book_ticket_from') )
    addClassValid( document.querySelector('#ticket_book_ticket_until') )
    document.querySelector(`.ticket_book_ticket_from`).textContent = ''
  }

  let tickets_index = 0
  form.append( "ticket_book[name]", document.querySelector('#ticket_book_name').value )
  for (let i =  ticket_from; i <= ticket_until; i++) {
      form.append( `ticket_book[tickets_attributes][${tickets_index}][number]`, i )
    tickets_index++
  }
  fetch('/ticket_books/', {
      method: 'POST',
      headers: {           
        'X-CSRF-Token': document.getElementsByName('csrf-token')[0].content,
      },
      body: form
    })
    .then( response => response.json() )
    .then( response => {
      if (response.status === 'success') {
        ticket_books_table.ajax.reload(null,false)
        $("#ticket_book_create").modal('hide')
        noty_alert(response.status, response.msg)
      } else {
        document.querySelector('#ticket_book_ticket_from').classList.remove('is-invalid')
        document.querySelector('#ticket_book_ticket_until').classList.remove('is-invalid')
        document.querySelector('#ticket_book_name').classList.remove('is-invalid')
        Object.entries(response.msg).forEach(([key, value]) => {
          let error_class = key.split('.')
          if (error_class[0] == "tickets") {
            addClassInvalid( document.querySelector('#ticket_book_ticket_from') )
            addClassInvalid( document.querySelector('#ticket_book_ticket_until') )
            document.querySelector(".ticket_book_ticket_from").textContent = value
          } else {
            addClassInvalid( document.querySelector('#ticket_book_name') )
            document.querySelector(".ticket_book_name").textContent = value
          }
        })
      }
    } )
    .catch( error => noty_alert('error', 'No se pudo registrar el talonario') )
})

app/views/ticket_books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket_book.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket_book.status %>
</p>

<p>
  <strong>Active:</strong>
  <%= @ticket_book.active %>
</p>

<%= link_to 'Edit', edit_ticket_book_path(@ticket_book) %> |
<%= link_to 'Back', ticket_books_path %>